services:
  pagamento-service:
    build:
      context: ./pagamento-service
      dockerfile: Dockerfile
    container_name: pagamento-service
    ports:
      - "3002:3002"
    depends_on:
      - pagamento-db
      - rabbitmq
    environment:
      SERVICE_NAME: pagamento-service
      SERVICE_PORT: 3002

      DB_HOST: pagamento-db
      DB_PORT: 5433
      DB_USER: pagamentouser
      DB_PASS: pagamentopass
      DB_NAME: pagamentodb

      RABBITMQ_URL: amqp://rabbitmq:5672
    restart: always

  pagamento-db:
    image: postgres:17-alpine
    container_name: pagamento-db
    environment:
      POSTGRES_USER: pagamentouser
      POSTGRES_PASSWORD: pagamentopass
      POSTGRES_DB: pagamentodb
    ports:
      - "5433:5433"
    volumes:
      - pagamento-db-data:/var/lib/postgresql/data


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pagamento-db-data: