services:
  rabbitmq:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - saga-networks

  pedido-service:
    build:
      context: ./pedido-service
      dockerfile: Dockerfile
    container_name: pedido-service
    ports:
      - "3001:3001"
    depends_on:
      - pedido-db
      - rabbitmq
    environment:
      SERVICE_NAME: pedido-service
      SERVICE_PORT: 3001
      DB_HOST: pedido-db
      DB_PORT: 5432
      DB_USER: pedidouser
      DB_PASS: pedidopass
      DB_NAME: pedidodb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - saga-networks
    restart: unless-stopped

  pedido-db:
    image: postgres:17-alpine
    container_name: pedido-db
    environment:
      POSTGRES_USER: pedidouser
      POSTGRES_PASSWORD: pedidopass
      POSTGRES_DB: pedidodb
    ports:
      - "5433:5432"
    volumes:
      - pedido-db-data:/var/lib/postgresql/data
    networks:
      - saga-networks

  pagamento-service:
    build:
      context: ./pagamento-service
      dockerfile: Dockerfile
    container_name: pagamento-service
    ports:
      - "3002:3002"
    depends_on:
      - pagamento-db
      - rabbitmq
    environment:
      SERVICE_NAME: pagamento-service
      SERVICE_PORT: 3002
      DB_HOST: pagamento-db
      DB_PORT: 5432
      DB_USER: pagamentouser
      DB_PASS: pagamentopass
      DB_NAME: pagamentodb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - saga-networks
    restart: unless-stopped

  pagamento-db:
    image: postgres:17-alpine
    container_name: pagamento-db
    environment:
      POSTGRES_USER: pagamentouser
      POSTGRES_PASSWORD: pagamentopass
      POSTGRES_DB: pagamentodb
    ports:
      - "5434:5432"
    volumes:
      - pagamento-db-data:/var/lib/postgresql/data
    networks:
      - saga-networks

  entrega-service:
    build:
      context: ./entrega-service
      dockerfile: Dockerfile
    container_name: entrega-service
    ports:
      - "3003:3003"
    depends_on:
      - entrega-db
      - rabbitmq
    environment:
      SERVICE_NAME: entrega-service
      SERVICE_PORT: 3003
      DB_HOST: entrega-db
      DB_PORT: 5432
      DB_USER: entregauser
      DB_PASS: entregapass
      DB_NAME: entregadb
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - saga-networks
    restart: unless-stopped

  entrega-db:
    image: postgres:17-alpine
    container_name: entrega-db
    environment:
      POSTGRES_USER: entregauser
      POSTGRES_PASSWORD: entregapass
      POSTGRES_DB: entregadb
    ports:
      - "5435:5432"
    volumes:
      - entrega-db-data:/var/lib/postgresql/data
    networks:
      - saga-networks

volumes:
  pedido-db-data:
  pagamento-db-data:
  entrega-db-data:

networks:
  saga-networks:
    driver: bridge